# Site settings
email: saa13b@my.fsu.edu
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: What Simon Said
description: A software engineer's musings on code, AI, and the digital frontier.
url: ""
twitter_username:
default_img: 

# Profile settings
name: Simon Aizpurua
profile_img: assets/images/img_8192.jpg
profile: I am a software engineer working remotely. I work on things that interest me. AI currently under the scope
.  github: http://www.github.com/Sharcee

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed
  sourcemap: never

# Gems
gems: [jekyll-paginate, jekyll-sitemap, jekyll-autoprefixer]
